# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBlkoZqj-lSxwS5nI8-mnvACciorNyKt
"""

a =int( input("digite o primeiro numero "))# Solicita ao usuário para digitar um número e converte o valor para inteiro
# Verifica se o número digitado é maior que zero
if a >= 0:
  print(a) # Se o número for maior que zero, imprime que o número é positivo
  print("o numero " ,a,"é positivo")# Se o número não for maior que zero, imprime que o núm ero é negativo
else:
  print(a)
  print("o numero " , a, "é negativo")



from re import A
# Solicita ao usuário para digitar "M" para Masculino ou "F" para Feminino
a = input("digite a letra F(feminino) ou M(masculino)")
#verifique se a opcao é a letra F
if a == "F" or a == "f":
  print("Você selecionou a opção feminino")
elif a == "M" or a == "m":
    print("Você selecionou a opção masculino")
else:
      print("Resposta invalida")
# Verifica se a entrada é "M" (Masculino)
# Se a entrada for "M", imprime "Sexo masculino" # Se a entrada não for
# Se a entrada não for nem "M" nem "F", imprime "Sexo invál i

# Solicita ao usuário que insira o preço do primeiro produto e armazena o valor em 'a'
a=input("digite o primeiro numero")
# Solicita ao usuário que insira o preço do segundo produtoe armazena o valor em 'b'
b=input("digite o primeiro numero")
# Solicita ao usuário que insira o preço do terceiro produto e armazena o valor em 'c'
c=input("digite o primeiro numero")
# Inicializa a variável 'menor' com um valor arbitrário
maior = 0
menor = 0
# Este valor será substituído posteriormente pelo valor do produto com menor preço
# Verifica qual é o menor preço entre 'a', 'b' e 'c'
if a > b and a > c:
  maior = a
  elif b > a and b > c:
    maior =

# Imprime o produto com o menor preço

a=input("por favor,digite uma letra ")
# Verifica se a letra digitada é 'a', 'e', 'i', 'o' ou 'u' (vogais)
if a == "A" or a == "a" or a =="E" or a == "e" or a =="I" or a == "i" or a == "O" or a == "o" or a == "U" or a =="u":
  print("voce digitou uma vogal")
 # Se a letra digitada for uma vogal, imprime "É uma vogal"
elif a == "B" or a == "b" or a == "C" or a == "c" or a == "D" or a == "d" or a == "F" or a == "F" or a == "G" or a == "g" or a == "H" or a == "h" or a == "J" or a == "j" or a == "K" or a == "k" or a == "L" or a == "l" or a == "M" or a == "m" or a == "N" or a == "n" or a == "P" or a == "p" or a == "Q" or a == "q" or a == "R" or a == "r" or a == "S" or a == "s" or  a == "T" or a == "t" or a == "V" or a == "v" or a == "W" or a == "w" or a == "X" or a == "x" or a == "Y" or a == "y" or a == "Z" or a == "z" :
 print("voce digitou uma consoante")
else:
 print("não identificado ")
# Se a letra digitada não for uma das vogais, imprime "não é uma vogal"

# Solicita ao usuário que insira a nota da primeira parcial e a armazena em 'parcial1'
nota1 = float(input("insira a nota da primeira parcial "))
# Solicita ao usuário que insira a nota da segunda parcial e a armazena em 'parcial2'
nota2 = float(input("insira a nota da segunda parcial "))
# Calcula a média das duas parciais
media =(nota1+nota2)/2
# Verifica se a média é igual a 10
# Se a média for igual a 10, imprime "Aprovado com distinção"
if media == 10:
  print("Aprovado com distinção")
# Se a média não for igual a 10, verifica se é maior ou igual a 7
# Se a média for maior ou igual a 7, imprime "Aprovado"
elif media >=7:
  print("Aprovado")
# Se a média não for nem igual a 10 nem maior ou igual a 7, imprime "Reprovado"
else:
  print("Reprovado")

# Solicita ao usuário que insira o primeiro número e armazena o valor em 'a'
a=float(input("INSIRA O PRIMEIRO NUMERO"))
# Solicita ao usuário que insira o segundo número e armazena o valor em 'b'
b=float(input("INSIRA O SEGUNDO NUMERO"))
# Solicita ao usuário que insira o terceiro número e armazena o valor em 'c'
c=float(input("INSIRA O TERCEIRO NUMERO"))
# Verifica se 'a' é maior que 'b' e 'c'
# Se 'a' for o maior, imprime 'a'
if a > b and a > c:
  print("o maior valor é ",a)
# Se 'a' não for o maior, verifica se 'b' é maior que 'a' e'c'
# Se 'b' for o maior, imprime 'b'
elif b > a and b > c:
  print("o maior valor é ",b)
# Se 'a' e 'b' não forem os maiores, 'c' deve ser o maior
# Se 'c' for o maior, imprime 'c'
else:
  print("o maior valor é",c)

# Solicita ao usuário que insira o primeiro número e armazena o valor em 'a'
a=float(input("INSIRA O PRIMEIRO NUMERO "))
# Solicita ao usuário que insira o segundo número e armazena o valor em 'b'
b=float(input("INSIRA O SEGUNDO NUMERO "))
# Solicita ao usuário que insira o terceiro número e armazena o valor em 'c'
c=float(input("INSIRA O TERCEIRO NUMERO "))
# Inicializa as variáveis 'maior' e 'menor' com valores arbitrários
maior = 0
menor = 0

# Estes valores serão substituídos posteriormente pelos valores reais dos números inseridos pelo usuário

# Verifica qual é o maior número entre 'a', 'b' e 'c'
if a > b and a > c:
  print("O maior valor e é",a)
  maior = a
elif b > a and b >c :
  print("O maior valor é",b)
  maior = b
else:
  print("O maior valor é",c)
  maior = c

# Verifica qual é o menor número entre 'a', 'b' e 'c'

if a < b and a < c:
  print("o menor valor é ",a)
elif b < a and b < c:
  print("o menor valor é ",b)
else:
  print("o menor valor é ",c)
# Imprime o maior e o menor números



print("bom dia amigo, hoje irei te ajudar a realizar o orçamento mais em conta pro seu bolso")
# Solicita ao usuário que insira o preço do primeiro produto e armazena o valor em 'a'
a=float(input("insira o valor do primeiro produto "))
# Solicita ao usuário que insira o preço do segundo produtoe armazena o valor em 'b'
b=float(input("insira o valor do segundo produto "))
# Solicita ao usuário que insira o preço do terceiro produto e armazena o valor em 'c'
c=float(input("insira o valor do terceiro produto "))
# Inicializa a variável 'menor' com um valor arbitrário
menor = 0
# Este valor será substituído posteriormente pelo valor doproduto com menor preço
# Verifica qual é o menor preço entre 'a', 'b' e 'c'
if a < b and a < c:
  print("o valor de menor preço é " ,a, "espero ter ajudado!")
elif b < a and b < c:
  print("o valor de menor preço é " ,b, "espero ter ajudado!")
else:
  print("o valor de menor preço é " ,c, "espero ter ajudado!")
# Imprime o produto com o menor preço

print("valores em ordem decrescente")
# Solicita ao usuário que insira três números e armazena os valores em 'a', 'b' e 'c'
a=float(input("INSIRA O PRIMEIRO NUMERO "))
# Solicita ao usuário que insira o segundo número e armazena o valor em 'b'
b=float(input("INSIRA O SEGUNDO NUMERO "))
# Solicita ao usuário que insira o terceiro número e armazena o valor em 'c'
c=float(input("INSIRA O TERCEIRO NUMERO "))
# Verifica todas as seis possíveis combinações de ordem dos três números e imprime a combinação na ordem não decrescente
if a > b and b > c:
  print(a,b,c)
elif b > a and a > c:
  print(b,a,c)
elif a > c and c > b:
  print(a,c,b)
elif b > c and c > a:
  print(b,c,a)
elif c > a and a > b:
  print(c,a,b)
else:
  print(c,b,a)

# Solicita ao usuário que insira o turno de estudo e armazena a entrada em 'a'
print("Ola aluno!")
print("SELECIONE UM PERIODO")
print("M-matutino")
print("V-vespertino")
print("N-noturno")
a=input("Insira o horario de estudo M-matutino ou V-vespertino ou N-noturno.")
if a == "m" or a == "M":
  print("Bom dia!")
elif a == "V" or a =="v":
  print("Boa tarde!")
elif a == "N" or a == "n":
  print("Boa noite!")
else:
  print("desculpe,não entendi")
# Verifica qual foi o turno inserido e imprime a saudação correspondente

a=float(input("insira o valor do primeiro produto "))
b=float(input("insira o valor do primeiro produto "))
if a>b:
  print("o maior valor é",a)
else:
  print("o maior valor é",b)

print("Selecione o dia da semana")
print("1-domingo")
print("2-segunda")
print("3-terça")
print("4-quarta")
print("5-quinta")
print("6-sexta")
print("7-sabado")
a=input("insira o numero correspondente  ")
if a == "1":
  print("domigo")
elif a == "2":
  print("segunda")
elif a== "3":
  print("terça")
elif a== "4":
  print("quarta")
elif a=="5":
  print("quinta")
elif a=="6":
  print("sexta")
elif a=="7":
  print("sabado")
else:
  print("não entendi")



#Faça um programa que leia 5 números e informe a soma e a média dos números.
for contador in range(5):
 numero=float(input("digite numero:"))
 numero_maior=0
 numero_maior==numero
if numero > numero_maior:
  print(numero maior")
else:4
 print("erro")

#Faça um programa que verifique e mostre os números entre 1.000 e 2.000
#(inclusive) que, quando divididos por 11 produzam resto igual a 2.
#verificar numeros
#mostrar numeros
#entre 1000
for contador in range(1000,2001):
  if contador % 11 == 2:
    print(contador)

maior_numero=0
for contador in range(5):
 numero=int(input("digite numero:"))
 if numero > maior_numero:
  maior_numero = numero
 print(maior_numero)

soma = 0
for n in range(5):
 numero=float(input(f"digite o {n+1}º numero:"))
 soma += soma/5
 print(f"a soma dos nos numeros é:{soma}")
 print(f"a media dos nos numeros é:{media}")

#Faça um programa que mostre as tabuadas dos números de 1 a 10 usando laços de repetição.
for tabuada in range(1,11):
 for numero in range(1,11):
   resultado = tabuada * numero
   print(f"{tabuada}X{numero}={resultado}")

#Faça um programa que imprima na tela os números de 1 a 20, um abaixo do outro. Depois modifique o programa para que ele mostre os números um ao lado do outro.
for numero in range(1,21):
  print(numero)